name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: "Install Dependencies"
      run: pnpm i

    - name: "Build command"
      run: pnpm build

  build-and-push-image:
    name: Build and Push Image
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PW }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/products-app-devops-frontend:latest .
          docker build -t ${{ secrets.DOCKERHUB_USER }}/products-app-devops-frontend:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/products-app-devops-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USER }}/products-app-devops-frontend:${{ github.sha }}