name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: "Install Dependencies"
      run: pnpm i

    - name: "Build command"
      run: pnpm build

  build-and-push-image:
    name: Build and Push Image
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PW }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/products-app-devops-frontend:latest .
          docker build -t ${{ secrets.DOCKERHUB_USER }}/products-app-devops-frontend:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/products-app-devops-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USER }}/products-app-devops-frontend:${{ github.sha }}
  
  update-helm-values:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Checkout Helm-Charts Repository
        uses: actions/checkout@v3
        with:
          repository: Lekkyjay/products-app-devops-helmcharts
          token: ${{ secrets.INFRA_ACCESS_TOKEN }}
          path: helm-charts

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.27.5/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Update Frontend Image in Helm Chart
        run: |
          cd helm-charts
          yq e '.image.tag = "${{ github.sha }}"' -i charts/frontend/values.yaml
          yq e '.image.repository = "${{ secrets.DOCKER_USERNAME }}/products-app-devops-frontend"' -i charts/frontend/values.yaml

      - name: Commit and Push Changes
        run: |
          cd helm-charts
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Updated frontend image to ${{ github.sha }}"
          git push origin main